### ISSUE TITLE
php regex question

### ISSUE THREAD

**Issue by Langlais115** [JaimePolop/RExpository#4]
What do you intend to match with this part of the **PHP Passwords** regex?
**define ?\('(?:\w*pass|\w*pwd|\w*user|\w*datab)**

Can you give some examples? as to be honest, I don't really see what do you try to match.

https://github.com/JaimePolop/RExpository/blob/74ca4898399fb9d39091d3319a73ffe78917a786/regex.yaml#L1173

**Comment by carlospolop** [comment]
The goal of that part of the regex is to detect when in PHP variables that contains any of the strings "pass" or "pwd" or "user" or "datab".

An example would be:
`define('password','randompassword');`

I think that answers your question, but feel free to reopen the issue if you have more suggestions
