### ISSUE TITLE
Please fix the mandrill regex key

### ISSUE THREAD

**Issue by jekpot1337xOut** [JaimePolop/RExpository#7]
mandrill regex key have issue, it will grab like this:

md-InsecureRequestWarning [ invalid ]
md-thisometext_1-xxxxxxxx [ invalid ]
md----------------------- [ invalid ]
md-HTTP_X_FORWARDED_PROTO [ invalid ]
md--4ae9-af44-ead9f9bc6ca7 [ invalid ]

please get more targeted text like this :

md-FwkwbYrDdEF7WLKS2JGHHw [ valid ]

Thank you

**Comment by jekpot1337xOut** [comment]
include this
md-4210-B3DA-015481AC392F [ invalid ]

**Comment by JaimePolop** [comment]
Hey I just changed it!!!

Thank you so much for the correction :D
